Repository hacktoberfest2k20/DataStructures-and-Algorithms, pull requests merged in 2020-10, with the labels that each got.

#67 Added balanced bracket checker
  balanced_brackets.cpp
Labels: hacktoberfest

#100 3sum is a well known problem frequently asked in interviews
  3sum.cpp
Labels: c++, hacktoberfest

#66 Added Lee's Algorithm
  Lees_algo.cpp
Labels: c++, hacktoberfest

#108 Modularize project
  .github/pull_request_template.md
  Algebra-and-Numerical-Methods/IntegerFactorizeAlgo.cpp
  Algebra-and-Numerical-Methods/SieveOfEratosthenes.cpp
  Data-Structures/BalancedBrackets.cpp
  Data-Structures/Hashing.c
  Data-Structures/SquareRootDecompostion.cpp
  Dynamic-Programming/KadanesAlgo.cpp
  Graphs/DFS.cpp
  Graphs/HeightOfBinaryTree.cpp
  Searching/BinarySearchIterative.cpp
  Searching/BinarySearchRecursion.cpp
  Searching/LinearSearch.cpp
  Sorting/BubbleSort.cpp
  Sorting/MergeSort.cpp
  Sorting/QuickSort.cpp
Labels: enhancement

#150 Implemented BubbleSort in Java
  Sorting/java/Bubble-Sort.java
Labels: community, hacktoberfest
